### ISSUE TITLE
BUG: Tribeca "forgets" to cancel order when pdiv + tbp is not respected

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#59] opened 2017-05-03 15:28 UTC
I realized that when apr gets activated, tribeca will not cancel the already open orders on the other side. Or not directly.

I come back to you when I have more details!

And thanks for the improvements,

A big well done !

**Comment by ctubio** [comment] 2017-05-03 16:49
thanks for the notice'¡ I will try to carefully look at APR functionality too

**Comment by ctubio** [comment] 2017-05-03 19:10
with Coinbase i have apr=off, and im getting like 10 zombie orders every day in the exchange that doesnt exists in the app too :(

you also see zombie orders in Coinbase? (for me OkCoin seems to work as expected)

**Comment by Camille92** [comment] 2017-05-04 09:04
Well, I run a small script to cancel all orders on Coinbase every 5 minutes, so I have to be very lucky to see that.

But I have seen the issue on OkCoin yes.

What usually happens is that:
Tribeca is trading both sides, then either one bullet is sold or TBP changes one of those activate the apr and tribeca stop selling.

Then a sell order stays there for a couple of minutes until it is eaten by the market (or maybe canceled by tribeca) but I'm not sure.

**Comment by Camille92** [comment] 2017-05-04 09:32
Found the perfect example from ETH/BTC (forgot to make the script work for them).

ETH/BTC
![capture d ecran 2017-05-04 a 11 26 44](https://cloud.githubusercontent.com/assets/6861590/25697798/afd2165a-30bc-11e7-9365-68cb7d634700.png)

BTC/USD:
![capture d ecran 2017-05-04 a 13 55 17](https://cloud.githubusercontent.com/assets/6861590/25702531/b5b85808-30d1-11e7-8092-6cbf502fbfab.png)

It's good because when I cancel them on the bot they don't reappear and when I cancel them from the exchange they don't reappear as well. 
Other good news when I cancel them from the exchange tribeca "sees" that they are not there anymore and don't show them on the 'order screen'.

It just looks like tribeca "forgets" to cancel them haha.

**Comment by Camille92** [comment] 2017-05-04 11:52
I dropped the cancel orders script for testing, I can confirm you that I see it in all the markets I'm trading in!
And it seems to go in the direction of what it is described on #60.

So to sum up it's a bug:
Tribeca doesn't cancel orders on the depleted side when tbp + pdiv conditions are not respected.

**Comment by ctubio** [comment] 2017-05-04 11:53
oh ok, i was talking then about another issue xD

thanks for your explanation/screenshot, i will try to look at this, but i didnt experiencied this since long time ago :S maybe i should ~try ETH/BTC~ enable apr

**Comment by Camille92** [comment] 2017-05-04 12:00
Well, on the other hand, I haven't seen any ghost order in a long time 😝 

I added a screenshot of BTC/USD as well on Coinbase, but I've seen it as well on OK

**Comment by ctubio** [comment] 2017-05-10 20:42
im not able to reproduce this anymore (had apr=on for several days), let me close this unless you disagree

**Closed as completed by ctubio** 2017-05-10 20:42 UTC
Labels: bug, acknowledged
