### ISSUE TITLE
Changing decimals of Tribeca

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#39] opened 2017-04-17 08:27 UTC
(Related to https://github.com/ctubio/tribeca/issues/31) 

Hello Carles,

i discovered that trading with LTC, now tribeca can only trade with 2 decimals but the LTC / USD market allows for 3 decimals.

It means that Tribeca only put orders on round cents and consequently doesn't manage to "get on top of the market" very often. 

Solution is to:
_ Allow for 3 decimals when trading LTC
_ Allow for 5 decimals for future LTC/BTC and ETH/BTC market.

Ps: I encourage you to try to trade on those markets as well, width is 5 to 10 times bigger!

**Comment by Camille92** [comment] 2017-04-17 09:29
If this the tol value we find in models ?

**Comment by ctubio** [comment] 2017-04-17 12:21
some are the tol value (http://www.c-jump.com/bcc/c157c/Week05/W05_0040_scientific_notation.htm) , others are because Utils.roundFloat and many other rounding functions everywhere working only with 2 decimals, and others are unkown; sorry i dont have more details/solutions now, i never used to trade LTC before so i never experiencied this before

**Comment by Camille92** [comment] 2017-04-17 12:23
Thanks for the details.

Yes same I didn't think about before!

**Comment by ctubio** [comment] 2017-04-17 12:52
my dog hit the close butoon sorry xD

but let me take profit and say: will need to rewrite everything in order to implement concurrent exchanges in a single app, so that may be the time to fix the decimals everywhere too; im a bit lazy about it but is in the roadmap definitely, some day, maybe!

**Comment by Camille92** [comment] 2017-04-17 13:01
I ididn't realize everything needs to be rewritten for that. Do you think it's worth ?

**Comment by ctubio** [comment] 2017-04-17 13:14
ouYea, evolution worth the time it takes, always

![trek_6](https://cloud.githubusercontent.com/assets/1634027/25089885/82b1756a-2380-11e7-9eeb-79b11b39d985.jpg)

**Comment by Camille92** [comment] 2017-04-17 13:35
I just thought about that for a quick and easy fix at my level before the big change:

What if i trick tribeca in the wrapper by telling it to multiply by 10 all the quotes it's receiving from the market and then dividing it by 10 before it goes out ?

Would that work?

**Comment by ctubio** [comment] 2017-04-17 13:41
yea it could work by translating the values in and out of the bridge of okcoin.ts gateway, but i would not do this just because of the confusion that it generates, instead i will go for the fix of the whole app. (i mean, you are left alone here i think'¡ :P)

**Comment by Camille92** [comment] 2017-04-17 14:42
Haha I have no chance to manage to fix the whole app, I'm going to give a try at translating the values!

**Comment by ctubio** [comment] 2017-04-18 19:37
not only the btc side, but also the usd side should have 8 decimals, because when trading btc/ltc, will need 8 decimals in both sides, no?

**Comment by Camille92** [comment] 2017-04-19 08:37
Did not think about it, but yes you're right !

**Comment by ctubio** [comment] 2017-04-19 11:59
Ok so ima add some internal variables to not only allow for the curencies to have a symbol, but also to have a defined decimal quantity; so this will be spread everywhere and used to round accordingly everywhere (cos i dont wanna have 8 decimals in eur or usd xD).

**Comment by Camille92** [comment] 2017-04-19 12:31
Sounds to be a clever way to do!
Can we use data sent by the exchange to define the decimal ?

**Comment by ctubio** [comment] 2017-04-22 20:07
see [michaelgrosner:more_currencies](https://github.com/michaelgrosner/tribeca/commits/more_currencies) branch

**Comment by Camille92** [comment] 2017-04-22 20:10
Seen! Good work :)

**Comment by Camille92** [comment] 2017-04-24 23:52
Still not working but soon!

https://github.com/michaelgrosner/tribeca/issues/100

**Comment by ctubio** [comment] 2017-04-25 00:33
just saying, i just merged from upstream the latest modifications, i didn't apply these modifications in the parts of the code that only exists in this fork yet (but will do soOn'¡ [maybe some issue are because of this discrepancy])

let me reopen this meanwhile the new rounding is not everywhere

**Comment by Camille92** [comment] 2017-04-25 00:47
Haha ok it makes sense as this version was not able to see the market correctly. :p

**Comment by ctubio** [comment] 2017-04-26 19:23
finally https://github.com/michaelgrosner/tribeca/issues/100 redirects to  https://github.com/michaelgrosner/tribeca/pull/102, that was just merged at https://github.com/ctubio/tribeca/pull/49, so closing'¡

(hope your issue is fixed, cos i was only able to test with EUR/USD/BTC)

**Comment by Camille92** [comment] 2017-04-29 21:15
Hello, I was testing it today on OkCoin LTC/USD.

It doesn't seems to work as tribeca still uses 2 decimals and not the 3 the market offers.

Do you know if it's due  from some parts of the code here?

I can have a look and help if you can orientate me where to look.

Best and nice weekend,

Camille

PS:
Totally non related question but do you have access to your tip address, I would have think that you would use the money for tribeca trading and not letting it there. Well anyway it's yours!

**Comment by ctubio** [comment] 2017-04-30 02:05
morning Camille''
i think even if the roundings are new, all quote values are still 2 decimals (and base values 8 decimals); will review it and try to apply minimum 3 decimals to quote values'¡

PS:
yes i have access to the private key of the git tip address, didnt wanted to invest the funds cos are lovely donations that deserve some respect xD thanks again'¡!

**Comment by ctubio** [comment] 2017-04-30 19:54
eeep Camille'''
sorry are you trying LTC on Coinbase or in what exchange? ty'¡
(is for try to reproduce asap your very same situation; and fix the rest later :P)

**Comment by Camille92** [comment] 2017-04-30 19:55
I was trying in OkCoin this time :)

Thanks for helping :)

**Comment by Camille92** [comment] 2017-05-01 12:38
![capture d ecran 2017-05-01 a 14 34 28](https://cloud.githubusercontent.com/assets/6861590/25579840/c81ebd8c-2e7b-11e7-8299-cb6f799f7876.png)

Sadly not working yet :/

**Comment by ctubio** [comment] 2017-05-01 13:46
sorry can you please briefly explain again your problem/situation? (i see all ok in your image and in my test i was able to send 3 decimals to okcoin [but i got error `10011 Amount too low` because i was using usd; maybe i should really use ltc xD])

**Comment by Camille92** [comment] 2017-05-01 13:56
Yes no problem.

Well basically, I should see the detail of the price for instance in the image we have several times 15.55 because one order is at 15.552 another 15.554 and the last one at 15.555.

And tribeca doesn't send orders with details smaller than 2 zeros after the coma at least in the trade logs I have orders are always at a round cent : 15.48, 15.49, 15.5 ...

The issue is that is makes "get on top of the market" useless: other traders can easily overcome Tribeca by sending orders of a 1/10 of a cent above it and tribeca would not see it or send orders a cent above (which is big in ltc terms).


I'm going to try to see if Michael's version work with it and if yes try to find where is the difference in the code.

>[but i got error 10011 Amount too low because i was using usd; maybe i should really use ltc xD])

Yes i got this error too, it comes from the fact that Tribeca's default settings is to send 0.01 orders and the LTC/USD market allows only for minimum trade size of 0.1 LTC ;)

**Comment by Camille92** [comment] 2017-05-01 15:21
Working on LTC/USD ! Thank you very much!

I did not try with the others market does it work as well ? :D

**Comment by ctubio** [comment] 2017-05-01 15:39
I think now LTC is niiiice, but donno other alts.

**Comment by Camille92** [comment] 2017-05-01 15:42
Haha Ok I'll tell you :)
I let it run for now and let you come back with some details in case of !

**Comment by Camille92** [comment] 2017-05-01 18:51
I tried this version and Michael's version and yours is not working with the alts on Gdax while the other do work.

Any idea why ?

Cheers!
![capture d ecran 2017-05-01 a 20 49 27](https://cloud.githubusercontent.com/assets/6861590/25590236/eae33d82-2eaf-11e7-88fc-0145f070d902.png)

**Closed as completed** 2017-05-02 18:37 UTC
Labels: improvement, acknowledged
