### ISSUE TITLE
Libquickfix.so.16 not finding error

### ISSUE THREAD

**Issue by b-seite** [ctubio/tribeca#135] opened 2017-06-13 19:52 UTC
Hello,
probably it´s me who is simply too stupid. 
But since 2 days i get the following Error when rebuilding and starting tribeca from node. I am using the latest versions of the repository and npm/node.

> Error: libquickfix.so.16: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/tribeca/node_modules/node-quickfix-wrap/index.js:1:78)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/tribeca/app/server/gateways/coinbase.js:23:18)
    at Module._compile (module.js:569:30)

has anyone an idea for me?
Thanks Boris

**Comment by ctubio** [comment] 2017-06-13 20:42
from tribeca folder try `rm -rf /usr/local/lib/libquickfix.so && npm run compile-quickfix` not sure why  libquickfix.so.16 doesn't exists so lets try to rebuild it. once is done if still fails, can you see what is the output of `ls -la  /usr/local/lib/libquickfix.so*`?
thanks'¡

**Comment by b-seite** [comment] 2017-06-13 22:19
I recompiled libquickfix. The problem is still there, here is the output of ls:

> [ec2-user@ip-xxx-xxx-xxx tribeca]$ ls -la /usr/local/lib/libquickfix.so*
lrwxrwxrwx 1 root root       21 Jun 13 22:09 /usr/local/lib/libquickfix.so -> libquickfix.so.16.0.1
lrwxrwxrwx 1 root root       21 Jun 13 22:09 /usr/local/lib/libquickfix.so.16 -> libquickfix.so.16.0.1
-rwxr-xr-x 1 root root 21192364 Jun 13 22:09 /usr/local/lib/libquickfix.so.16.0.1

**Comment by ctubio** [comment] 2017-06-13 23:03
well, seems libquickfix.so is OK so maybe the problem is in the node-quickfix-wrap, try if you agree from tribeca folder `rm -rf node_modules app build package-lock.json && git checkout package-lock.json && npm install`
thanks'¡

**Comment by ctubio** [comment] 2017-06-13 23:07
if still doesn't work, can you please manually check if you have installed all dependencies from http://www.quickfixengine.org/quickfix/doc/html/dependencies.html? is supposed that `npm install` will install all of them, but maybe i missed something?

**Comment by b-seite** [comment] 2017-06-14 08:37
I checked it but everything is installed correctly. 
The error still persist even on a brand new instance.

**Comment by ctubio** [comment] 2017-06-17 19:10
a new instance of what? can you please show the output of `cat /etc/issue && uname -a`? im not able to reproduce this in any of my Debian/CentOS/macOS
thanks'¡

**Comment by ctubio** [comment] 2017-06-18 16:06
allow me to close this meanwhile im not able to reproduce it, if you still have issues consider to paste the log of the whole fresh `npm install`, it may have an interesting error in there (after the app is executed it just misses the lib but doesnt say why it was not able to install it, so app execution log is not interesting)

**Closed as completed by ctubio** 2017-06-18 16:06 UTC
Labels: question

**Comment by b-seite** [comment] 2017-06-19 13:11
Thanks for the Help.
It seems that it was a special thing with Amazon Linux AMI 2017.03.0 which i used. 
At the moment i have no more problems using ubuntu 16.04
