### ISSUE TITLE
(BUG) Coinbase LTC/BTC & ETH/BTC markets don't work

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#134] opened 2017-06-13 11:42 UTC
Hello again Carles,

First of all, thanks for implementing the FIX API a Coinbase !
Just to know, do you have any stats about it ? It is actually faster ? I've never used FIX before so I'm not sure what's the performance difference between FIX and Websocket ^^".

Now the main issue, I don't know why but no order is sent on the LTC/BTC and ETH/BTC market with the new version.

Everything looks fine, I get my balance, it's connected from the exchange, the market is updated etc... but no order is sent!

Any idea why?

PS: It might be interesting to put that somewhere in the notes but for FIX to work, I had to create an API key for each market!

**Comment by ctubio** [comment] 2017-06-13 11:44
thanks for the report of the multiple api keys! is true it said that in the docs, i will add to our docs too

about your bug, im not able to reproduce it, can you try to simply restart the app? because https://github.com/ctubio/tribeca/issues/131

**Comment by Camille92** [comment] 2017-06-13 12:02
I did it and nothing changes did you try to run all the markets together?

**Comment by Camille92** [comment] 2017-06-13 12:34
FOUND IT!
The error seems to come with the % option.

When it's desactivated it works but it is blocked when activated :/

**Comment by ctubio** [comment] 2017-06-13 16:31
answering to your speed question: FIX is as fast as WebSocket, but Coinbase WebSocket is only for market data; to place orders we can use only HTTPS calls or FIX (so we use FIX).

**Comment by ctubio** [comment] 2017-06-13 16:33
about your bug, im not able to reproduce it yet, i switched also `%` but found no impact; i would say that all my Coinbase bots are working OK

**Comment by Camille92** [comment] 2017-06-13 16:35
Thank you for the update on FIX. :)

For the bug, when you go from % "unswitched" to "switched" the last orders still appear on the UI, but if you check on gdax website nothing is there.

Can you please check if it is the same for you?

**Comment by ctubio** [comment] 2017-06-13 16:59
is true that the last order remains in the UI after all have been canceled (so in the market theres not really any open order).

but this have nothing to do with the ability to continue trading, as soon as is decided to place a new order, it happens OK.

the confusion may be that for whatever other reason the app is not deciding to place orders, maybe some quoting parameters are blocking orders for the side that you expect to have orders?

**Comment by ctubio** [comment] 2017-06-13 17:04
tribeca shows orders in the UI when order are canceled IF quoting state for that side is off (still looking for a fix, but is just a cosmetic)

**Comment by Camille92** [comment] 2017-06-13 17:06
Yes, that's not very important.

I don't know what that can be, I used the same settings that worked as expected but since I updated yesterday afternoon it didn't work. I'll try to find where that comes from

**Comment by ctubio** [comment] 2017-06-13 17:10
IF in the logs you see `FIX Initiator Started` and `Logon true`, mean that the connection is OK, so the problem may be some settings in the quoting parameters

im sorry it happened to me too much times this, so i believe is your issue too; but i keep monitoring my Coinbase bots in case i notice something similar not related to the ethernal human errors

**Comment by ctubio** [comment] 2017-06-13 17:12
hope you don't mind if i close the issue meanwhile im not able to reproduce it, still is open in my heart and brain :dancer: (lets debug!)

**Closed as completed by ctubio** 2017-06-13 17:12 UTC
Labels: improvement, acknowledged

**Comment by ctubio** [comment] 2017-06-13 17:16
another thing we can do is if you paste/screenshot me somehow your settings i can try them and see if happens the same, not sure if we have other options

**Comment by Camille92** [comment] 2017-06-13 17:50
Yes I'll do that!
I think the fix connection works well because it trades when I change the
settings.
I'll do that when I go home :)

**Comment by Camille92** [comment] 2017-06-14 12:57
I post that here!

See here, the % is off and the bot is trading:

![capture d ecran 2017-06-14 a 14 54 52](https://user-images.githubusercontent.com/6861590/27133199-abe29464-5111-11e7-82dd-8486c49ab171.png)


When I turn it on -> it stops!
![capture d ecran 2017-06-14 a 14 57 15](https://user-images.githubusercontent.com/6861590/27133237-cba711bc-5111-11e7-9cf3-32a288d8e95f.png)
