### ISSUE TITLE
Price Too Precise Messages

### ISSUE THREAD

**Issue by beegmon** [ctubio/tribeca#47] opened 2017-04-25 00:08 UTC
Hello,

I am giving your fork of Tribeca a spin with it's interesting AK-47 strategy and I am seeing a lot these in the logs. To be fair I am currently only experimenting, but I am also running really small and tight bullet range, ping/ping width and size.

I pulled from master as of an hour or so and am seeing a lot of these in the logs:

{ message: 'price too precise (1257.6200000000001)' }","time":"2017-04-24T23:56:18.256Z","v":0}

This are posted several times per second. The overall effect is a significant reduction in accepted trades on the exchange, or at least it appears that way. I can reduce these messages by increasing the range and width parameters, but that also doesn't currently suit my testing purposes. Any hints or pointers would be greatly appreciated.

Thanks!

**Comment by ctubio** [comment] 2017-04-25 00:23
maybe #44 is not really fixed; i didn't saw that error in my logs never but will reinvestigate'¡

thanks for your report'¡

**Comment by Camille92** [comment] 2017-04-26 10:27
Fixed there apparently:
https://github.com/michaelgrosner/tribeca/commit/ef51333bf72cda81f5105a360f130e8015d5db40

**Comment by ctubio** [comment] 2017-04-26 11:34
sorry this commit just removed the always-present USD dollar symbols in the grids; in our fork we do not remove the symbols, instead we show the symbol of ANY currency, not just USD dollars

**Comment by ctubio** [comment] 2017-04-26 11:37
true, coinbase gateway seems to have now improved decimal precision, I will merge it asap at #49'¡

**Comment by ctubio** [comment] 2017-04-27 23:14
I was able to reproduce this :D thanks again'¡!

**Comment by Xagire** [comment] 2017-05-01 22:32
Also have it with code from 4 hours ago:

{"name":"tribeca:gateway:CoinbaseOE","hostname":"xxxxxx","pid":14,"level":40,"msg":"WARNING FROM GATEWAY: xxxxxx null { message: 'price too precise (0.05346000000000001)' }","time":"2017-05-01T22:31:29.726Z","v":0}

**Comment by ctubio** [comment] 2017-05-01 22:38
it was with BTC/USD?

**Comment by Xagire** [comment] 2017-05-02 11:56
It is with ETH/BTC

**Comment by ctubio** [comment] 2017-05-02 18:45
i can't reproduce the error anymore (again), hope is fixed with the last commit'¡!

**Closed as completed by ctubio** 2017-05-02 18:45 UTC
Labels: bug, acknowledged

**Comment by Xagire** [comment] 2017-05-02 19:48
Works fantastic! Thanks!
